name: npm release

on:
  push:
    tags:
      - "*-connector"

permissions:
  contents: write
  id-token: write

jobs:
  npm-release-test:
    runs-on: macos-latest
    environment: npm
    steps:
      - name: Download Source
        uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 7.33.6

      # Update npm to the latest version to enable OIDC
      - name: Update npm
        run: |
          npm install -g npm@latest
          npm --version

      - name: Build debug-router-connector
        run: |-
          set -e
          pushd debug_router_connector/

          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [[ $TAG_NAME == *"-connector"* ]]; then
            version=${TAG_NAME%-connector}
            echo "debug-router-connector version: $version"
            npm version --no-git-tag-version $version
          fi

          npm install
          npm run build
          ls -al

          if [[ $version == *"alpha"* ]]; then
              echo "Publishing alpha version..."
              npm publish --tag alpha
          else
              echo "Publishing stable version..."
              npm publish
          fi

          popd
