name: Publish Pod

on:
  push:
    tags:
      - '*-ios'
  workflow_dispatch:

jobs:
  publish-pod:
    runs-on: lynx-darwin-14-medium
    steps:
      - name: Download Source
        uses: actions/checkout@v4.2.2
      - name: Get Tag Information
        run: |-
          version=$(echo ${{ github.ref }} | awk -F "/" '{print $3}')
          echo "VERSION=${version%-ios}" >> $GITHUB_OUTPUT;
        id: get_tag
      - name: Push to Specs Repo
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.REPO_DEBUG_ROUTER_COCOAPODS_TRUNK_TOKEN }}
          POD_VERSION: ${{ steps.get_tag.outputs.VERSION }}
        run: |-
          pod repo add-cdn trunk https://cdn.cocoapods.org/
          COCOAPODS_TRUNK_TOKEN=$COCOAPODS_TRUNK_TOKEN POD_VERSION=$POD_VERSION pod trunk push DebugRouter.podspec  --skip-import-validation --allow-warnings
