name: Publish Pod

on:
  push:
    tags:
      - "*-ios"
  workflow_dispatch:

jobs:
  publish-pod:
    runs-on: macos-13
    steps:
      - name: Download Source
        uses: actions/checkout@v4.2.2
      - name: Bundle Install
        run: |-
          root_dir=$(pwd) && SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk bundle install
      - name: Get Tag Information
        run: |-
          version=$(echo ${{ github.ref }} | awk -F "/" '{print $3}')
          echo "VERSION=${version%-ios}" >> $GITHUB_OUTPUT;
        id: get_tag
      - name: Prepare cocoapods publish source
        env:
          VERSION: ${{ steps.get_tag.outputs.VERSION }}
        run: |-
          source tools/envsetup.sh
          tools/hab sync .
          python3 -m pip install requests
          python3 -m pip install PyYAML
          export POD_VERSION=$VERSION && export PACKAGE_ENV=prod && geniospkg --repo DebugRouter --tag ${{ env.VERSION }} --public_repo
      - name: Push iOS SDK to release
        env:
          VERSION: ${{ steps.get_tag.outputs.VERSION }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "${{ github.workspace }}/*.zip"
          replacesArtifacts: true
          allowUpdates: true
      - name: Push to Specs Repo
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.REPO_DEBUG_ROUTER_COCOAPODS_TRUNK_TOKEN }}
          POD_VERSION: ${{ steps.get_tag.outputs.VERSION }}
        run: |-
          pod repo add-cdn trunk https://cdn.cocoapods.org/
          COCOAPODS_TRUNK_TOKEN=$COCOAPODS_TRUNK_TOKEN pod trunk push DebugRouter.podspec.json  --skip-import-validation --allow-warnings
