name: remote-debug-driver npm release

on:
  push:
    tags:
      - "*-remote-debug-driver"

permissions:
  contents: write
  id-token: write

jobs:
  npm-release-test:
    runs-on: macos-latest
    environment: npm
    steps:
      - name: Download Source
        uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 7.33.6

      # Update npm to the latest version to enable OIDC
      - name: Update npm
        run: |
          npm install -g npm@latest
          npm --version

      - name: Build remote-debug-driver
        run: |-
          set -e
          pushd remote_debug_driver/

          TAG_NAME=${GITHUB_REF#refs/tags/}
          if [[ $TAG_NAME == *"-remote-debug-driver"* ]]; then
            version=${TAG_NAME%-remote-debug-driver}
            echo "remote-debug-driver version: $version"
            npm version --no-git-tag-version $version
          fi

          npm install
          npm run build
          ls -al
          npm publish --tag alpha
          popd
