#use_frameworks!
platform :ios, '9.0'

target 'DebugRouter_Example' do
  pod 'DebugRouter', :path => '../../../'
  pod 'SocketRocket', :git => 'git@github.com:facebookincubator/SocketRocket.git', :tag => '0.6.0'
end

target 'DebugRouter_Tests' do
  pod 'DebugRouter', :path => '../../../'
end
